Homework02
IuriiRadomskii/iurii-radomskii-homework pull request #2
Opened 2021-10-26 16:43 UTC by IuriiRadomskii

2021-10-31 08:49 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +    protected String getExpectedUserNameAtPage() {
moved credentials get-methods to static initializer

2021-10-31 08:50 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/credentials.properties
> +
Checkstyle: File does not end with a newline.

2021-10-31 09:07 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +        return null;
implemented void set-methods instead of String get-methods

2021-10-31 09:20 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +    private void assertCheckBoxes(List<WebElement> checkBoxes, WebDriver driver,
assertion methods moved to ex2 class

2021-10-31 09:39 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +public class BaseTest {
added

2021-10-31 09:39 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +    public void setupChromeDriver() {
done

2021-10-31 09:41 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +    private SoftAssertions softly = null;
There is no purpose. I removed this initialization.

2021-10-31 09:43 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +        driver = null;
I don't get it.

2021-10-31 09:43 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +    public void clear() {
done

2021-10-31 09:46 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +@SuppressWarnings("checkstyle:Indentation")
Removed. I suppose it was written accidentally.

2021-10-31 09:48 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +public class ExerciseTwoTest extends BaseTest {
fixed as in hw1

2021-11-01 14:36 UTC, ZeroShadows requested changes

2021-11-01 14:36 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +    @BeforeMethod
This should be in BaseTest

2021-11-01 14:36 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +    @AfterMethod
softly.assertAll() doesn't have to be in AfterMethod.
You could place in test body

2021-11-01 14:36 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +    private void setUpPage() {
Should be in BaseTest

2021-11-01 14:36 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +    private void assertAll() {
softly.assertAll() doesn't have to be in AfterMethod. You could place in test body

2021-11-01 14:36 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/credentials.properties
> +
So, it says does not end, not does not starts

2021-11-02 17:22 UTC, ZeroShadows requested changes

2021-11-02 17:22 UTC, ZeroShadows commented on pom.xml
>      <profiles>
where are the first hw profile?

2021-11-02 17:22 UTC, ZeroShadows commented on pom.xml
> +            <version>4.4.3</version>
why is webdrivermanager version here?

2021-11-02 17:22 UTC, ZeroShadows commented on .gitignore
> +src/main/java/Draft.java
What is that file? 
Why this file is ignored? 
This file don't have to be commited instead of inserting it into .gitignore

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/credentials.properties
> +
Not fixed

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +        driver.manage().window().maximize();
move it ot Before method

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +        driver.manage().window().maximize();
move it to Before method

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +        WebElement toggleBtn = new WebDriverWait(driver, Duration.ofSeconds(2))
you can define one implicit wait for every element instead of use WebDriverWait for every element on the page.
Should be defined in Before method.

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex1/ExerciseOneTest.java
> +        WebElement loginBtn = new WebDriverWait(driver, Duration.ofSeconds(2))
you can define one implicit wait for every element instead of use WebDriverWait for every element on the page. Should be defined in Before method.

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +    protected static void setExpectedUserNameAtPage() {
lets get rid off this methods.
refactor in that way and get property by the key from file
https://www.baeldung.com/java-properties

2021-11-02 17:22 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +    static {
remove it and refactor work with properties in that way https://www.baeldung.com/java-properties

2021-11-03 12:01 UTC, ZeroShadows requested changes

2021-11-03 12:01 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/BaseTest.java
> +    @BeforeMethod
1. What is the difference between BeforeClass and BeforeMethod? https://testng.org/doc/documentation-main.html#annotations
2. Why did you decide to separate it into two different methods?

2021-11-03 12:01 UTC, ZeroShadows commented on src/test/java/com/epam/tc/hw2/ex2/ExerciseTwoTest.java
> +        driver.manage().window().maximize();
why it still here btw?

2021-11-03 12:01 UTC, ZeroShadows commented on pom.xml
>      <profiles>
hw1 profile missed

2021-11-03 13:43 UTC, ZeroShadows approved these changes

2021-11-03 13:48 UTC, merged