Homework03
IuriiRadomskii/iurii-radomskii-homework pull request #3
Opened 2021-11-01 17:34 UTC by IuriiRadomskii

2021-11-07 13:04 UTC, ZeroShadows requested changes

2021-11-07 13:04 UTC, ZeroShadows commented on src/test/resources/com.epam.tc.hw3.test_suits/ex1-test-suite
> +<suite name="homework03-ex1-test-suite">
both test should be in one xml file

2021-11-07 16:02 UTC, IuriiRadomskii commented on src/test/resources/com.epam.tc.hw3.test_suits/ex1-test-suite
> +<suite name="homework03-ex1-test-suite">
both test classes are moved to single test suit

2021-11-08 13:30 UTC, ZeroShadows approved these changes

2021-11-08 13:43 UTC, merged