Homework07 jdi
IuriiRadomskii/iurii-radomskii-homework pull request #7
Opened 2021-11-22 14:52 UTC by IuriiRadomskii

2021-11-25 17:19 UTC, cold-flame requested changes

2021-11-25 17:19 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/tests/MetalsAndColorsTest.java
> +        homePage.open();
mb need to use this methods inside login() ?

2021-11-25 17:19 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/site/pages/BasePage.java
> +public class BasePage extends WebPage {
what do this page ?

2021-11-25 17:19 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/MetalAndColorsMainSection.java
> +public class MetalAndColorsMainSection extends Section {
mb it's Form ?

2021-11-28 16:37 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw7/site/pages/BasePage.java
> +public class BasePage extends WebPage {
This class contains common fields and methods for all pages. For example header, left-side navigation menu etc. This class implements "DRY" principle.

2021-11-28 16:39 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/MetalAndColorsMainSection.java
> +public class MetalAndColorsMainSection extends Section {
That's right. I refactored it. And override in-built Form<T> method fill().

2021-11-30 16:40 UTC, cold-flame requested changes

2021-11-30 16:40 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/MetalAndColorForm.java
> +    //@Css(".vertical-group .checkbox") public List<WebElement> elements;
Remove comment

2021-11-30 16:40 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/MetalAndColorForm.java
> +    private void selectElements() {
Why this method is empty ?

2021-11-30 16:40 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/Summary.java
> +    public Summary() {
why this method is empty ?

2021-11-30 17:45 UTC, cold-flame requested changes

2021-11-30 17:45 UTC, cold-flame commented on src/test/java/com/epam/tc/hw7/data/Info.java
> +    public List<String> summary;
Why you use access modifiers public for this fields? You also create methods (getters) with public access modifiers, e.g. getSummary(). Change public -> private for fields

2021-11-30 18:14 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/MetalAndColorForm.java
> +    //@Css(".vertical-group .checkbox") public List<WebElement> elements;
removed

2021-11-30 18:15 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/MetalAndColorForm.java
> +    private void selectElements() {
removed

2021-11-30 18:15 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw7/site/components/pages/metalsandcolors/Summary.java
> +    public Summary() {
also removed

2021-11-30 18:16 UTC, IuriiRadomskii commented on src/test/java/com/epam/tc/hw7/data/Info.java
> +    public List<String> summary;
done, private fields was made public

2021-12-01 08:23 UTC, cold-flame approved these changes

2021-12-01 11:38 UTC, merged